// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineShop.Db;

namespace OnlineShop.Db.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240516172442_AddFirstProducts")]
    partial class AddFirstProducts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OnlineShop.Db.Models.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<Guid?>("CartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Time")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("WishlistId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WishlistId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3c5a6e0e-7117-4c32-b5f4-8dc7ee4defeb"),
                            Cost = 3990m,
                            Description = "Death Stranding — компьютерная игра в жанре action с открытым миром, разработанная студией Kojima Productions в сотрудничестве с Guerrilla Games и изданная Sony Interactive Entertainment для PlayStation 4 в 2019 году. В 2020 году компания 505 Games выпустила версию игры для Microsoft Windows. 30 января 2024 года состоялся релиз версии для macOS и iOS. Это первая игра Хидэо Кодзимы и Kojima Productions после разрыва с Konami в 2015 году. В работе над игрой приняли участие актёры Норман Ридус, Мадс Миккельсен, Леа Сейду, Маргарет Куэлли, Томми Дженкинс, Линдси Вагнер и Трой Бейкер; в игре также появляются персонажи, моделями для внешности которых послужили кинорежиссёры Гильермо дель Торо и Николас Виндинг Рефн.",
                            ImgLink = "/images/DeathStranding.jpeg",
                            Name = "Death Stranding"
                        },
                        new
                        {
                            Id = new Guid("96dd3d74-e971-40c5-932b-0e031f15423a"),
                            Cost = 2790m,
                            Description = "Days Gone (дословно c англ. — «Минувшие дни»; в официальной русской локализации — «Жизнь после») — компьютерная игра в жанре action-adventure в открытом мире, разработанная американской студией Bend Studio и изданная компанией Sony Interactive Entertainment. Действие игры разворачивается на территории штата Орегон через два года после начала глобальной пандемии, превратившей большую часть населения в зомби, именуемых в игре «фриками». Игрок берёт на себя роль байкера Ди́кона Сент-Джона, который пытается выжить в суровом мире, практически полностью уничтоженном из-за эпидемии. В основе сюжета — поиски жены Дикона Сары, на момент событий игры считающейся мёртвой. Игровой процесс Days Gone ведётся от третьего лица и построен на исследовании открытого мира. Игрок может использовать огнестрельное оружие, оружие ближнего боя и «импровизированные» виды орудий, чтобы защитить себя от враждебных бандитов и «фриков». Основным средством передвижения по миру является мотоцикл, который можно улучшать и изменять его внешний вид.",
                            ImgLink = "/images/DaysGone.jpg",
                            Name = "Days Gone"
                        },
                        new
                        {
                            Id = new Guid("84dc641c-bd66-4545-87b7-fe578411a874"),
                            Cost = 1600m,
                            Description = "Infamous: Second Son (стилизовано как inFAMOUS: Second Son, в русской локализации — «Infamous: Второй Сын») — компьютерная игра в жанре action-adventure с открытым миром, разработанная американской студией Sucker Punch Productions и изданная компанией Sony Computer Entertainment в марте 2014 года эксклюзивно для игровой консоли PlayStation 4. Игра является третьей в серии Infamous. Главным героем является Делсин Роу, обладающий сверхспособностями, которые он использует в бою и во время путешествий по Сиэтлу, который является местом действия событий Second Son. По ходу игры Делсин приобретает новые способности и становится либо героем, либо злодеем, поскольку выборы игрока влияют на сюжет, концовку и на сами силы.",
                            ImgLink = "/images/InfamousSecondSon.jpg",
                            Name = "Infamous Secong son"
                        },
                        new
                        {
                            Id = new Guid("3ef21e93-f308-4581-8d18-3c6b93d92d88"),
                            Cost = 3990m,
                            Description = "Red Dead Redemption 2 (стилизованно — Red Dead Redemption II, сокращённо RDR2) — компьютерная игра в жанрах action-adventure и шутера от третьего лица с открытым миром, разработанная Rockstar Studios и выпущенная Rockstar Games для консолей PlayStation 4 и Xbox One 26 октября 2018 года и для персональных компьютеров под управлением Windows 5 ноября 2019 года. Является третьей игрой в серии Red Dead и приквелом к Red Dead Redemption 2010 года.\r\n\r\nДействие Red Dead Redemption 2, оформленной в духе вестерна, происходит на территории нескольких вымышленных штатов США на рубеже XIX—XX веков. Сюжет игры построен вокруг приключений банды Датча Ван дер Линде; под управлением игрока находится один из членов банды — Артур Морган, а после прохождения сюжетной линии до эпилога — другой член банды, Джон Марстон. После неудачного ограбления парома бандиты вынуждены скрываться в глуши от федеральных агентов и охотников за головами",
                            ImgLink = "/images/RDR2.jpeg",
                            Name = "Red dead redemption 2"
                        },
                        new
                        {
                            Id = new Guid("3adb9654-464a-499a-8cb6-f626beba82fd"),
                            Cost = 2990m,
                            Description = "God of War (с англ. — «Бог войны») — компьютерная игра в жанре action-adventure, разработанная компанией SIE Santa Monica Studio и изданная Sony Interactive Entertainment для игровой консоли PlayStation 4, а затем на Windows. Вышла 20 апреля 2018 года. Является восьмой игрой серии God of War, а также сиквелом к игре 2010 года God of War III. Игра продолжает события предыдущих игр и переносит серию в мир скандинавской мифологии — все предыдущие игры серии были основаны на греческой мифологии. 16 сентября 2020 года было анонсировано продолжение игры.",
                            ImgLink = "/images/GOW.webp",
                            Name = "God of war"
                        });
                });

            modelBuilder.Entity("OnlineShop.Db.Models.Wishlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.CartItem", b =>
                {
                    b.HasOne("OnlineShop.Db.Models.Cart", null)
                        .WithMany("CartItems")
                        .HasForeignKey("CartId");

                    b.HasOne("OnlineShop.Db.Models.Order", null)
                        .WithMany("CartItems")
                        .HasForeignKey("OrderId");

                    b.HasOne("OnlineShop.Db.Models.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.Product", b =>
                {
                    b.HasOne("OnlineShop.Db.Models.Wishlist", null)
                        .WithMany("WishListItems")
                        .HasForeignKey("WishlistId");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.Order", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.Product", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.Wishlist", b =>
                {
                    b.Navigation("WishListItems");
                });
#pragma warning restore 612, 618
        }
    }
}
